### PR TITLE
Add onchange effect datepicker

### PR DESCRIPTION
**Pull request by nickbristow**
## Background
Date value is lost when another component is changed. This change looks for change in onChange and resets the date.

## GitHub Issue
https://github.com/ctoec/component-library/issues/137

### CODE REVIEW

**Review by vonbearshark — APPROVED** [review]
Frustrating, but code-wise this lgtm and makes sense with the context

**Comment by JordanGuinn** [comment]
Reminder to: put the corresponding GitHub issue in the PR description,

**Comment by JordanGuinn** [comment]
@nickbristow Reminder to:

1. Put the GitHub issue URL in the PR description, so one's connected to the other in Zenhub
2. Explicitly request reviews from those you want to look at this PR

**Comment by JordanGuinn** [comment]
Also are these commits not [signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)?

**Review by JordanGuinn — APPROVED** [review]

**Pull request closed without merging**
